version: '3'
services:

  nginx:
    image: tonyyb/laravel-nginx:${NGINX_VERSION}
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      # - "8043:443"
    volumes:
      - ${FOLDER}:/var/www
    networks:
      - app-network

  php-fpm:
    build:
      context: ./php/${PHP_VERSION}
    restart: unless-stopped
    container_name: php
    tty: true
    volumes:
      - ${FOLDER}:/var/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
      DB_CONNECTION: "mysql"
      DB_HOST: "mysql"
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: 'root'
      DB_PASSWORD: '.'
      COMPOSER_MEMORY_LIMIT: -1

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app-network

  redis:
      image: redis:${REDIS_VERSION}
      container_name: redis
      restart: unless-stopped
      tty: true
      ports:
        - "6379:6379"
      networks:
        - app-network

volumes:
  mysqldata:
    driver: local

networks:
  app-network:
    driver: bridge
